#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1407177296.06553
__CHEETAH_genTimestamp__ = 'Mon Aug  4 11:34:56 2014'
__CHEETAH_src__ = 'templates/module_declaration.tmpl'
__CHEETAH_srcLastModified__ = 'Sun Aug  3 23:34:18 2014'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class module_declaration(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(module_declaration, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''module ''')
        _v = VFFSL(SL,"name",True) # u'${name}' on line 1, col 8
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 1, col 8.
        write(u'''(
''')
        i = 1
        for port in VFFSL(SL,"ports",True): # generated from line 3, col 1
            if VFFSL(SL,"port.width",True) > 1: # generated from line 4, col 1
                w = VFFSL(SL,"port.width",True) - 1
                write(u'''    ''')
                _v = VFFSL(SL,"port.dir",True) # u'${port.dir}' on line 6, col 5
                if _v is not None: write(_filter(_v, rawExpr=u'${port.dir}')) # from line 6, col 5.
                write(u'''put [''')
                _v = VFFSL(SL,"w",True) # u'$w' on line 6, col 21
                if _v is not None: write(_filter(_v, rawExpr=u'$w')) # from line 6, col 21.
                write(u''': 0] ''')
                _v = VFFSL(SL,"port.name",True) # u'${port.name}' on line 6, col 28
                if _v is not None: write(_filter(_v, rawExpr=u'${port.name}')) # from line 6, col 28.
            else: # generated from line 7, col 1
                write(u'''    ''')
                _v = VFFSL(SL,"port.dir",True) # u'${port.dir}' on line 8, col 5
                if _v is not None: write(_filter(_v, rawExpr=u'${port.dir}')) # from line 8, col 5.
                write(u'''put ''')
                _v = VFFSL(SL,"port.name",True) # u'${port.name}' on line 8, col 20
                if _v is not None: write(_filter(_v, rawExpr=u'${port.name}')) # from line 8, col 20.
            if VFFSL(SL,"i",True) != VFFSL(SL,"len",False)(VFFSL(SL,"ports",True)): # generated from line 10, col 1
                write(u''',
''')
            else: # generated from line 12, col 1
                write(u'''
''')
            i = VFFSL(SL,"i",True) + 1
        write(u''');
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_module_declaration= 'respond'

## END CLASS DEFINITION

if not hasattr(module_declaration, '_initCheetahAttributes'):
    templateAPIClass = getattr(module_declaration, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(module_declaration)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=module_declaration()).run()


