#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1407177296.051532
__CHEETAH_genTimestamp__ = 'Mon Aug  4 11:34:56 2014'
__CHEETAH_src__ = 'templates/module_instantiation.tmpl'
__CHEETAH_srcLastModified__ = 'Sun Aug  3 23:21:51 2014'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class module_instantiation(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(module_instantiation, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        if VFFSL(SL,"len",False)(VFFSL(SL,"params",True)) == 0: # generated from line 1, col 1
            _v = VFFSL(SL,"module_name",True) # u'$module_name' on line 2, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$module_name')) # from line 2, col 1.
            write(u''' ''')
            _v = VFFSL(SL,"instance_name",True) # u'${instance_name}' on line 2, col 14
            if _v is not None: write(_filter(_v, rawExpr=u'${instance_name}')) # from line 2, col 14.
            write(u'''(
''')
        elif VFFSL(SL,"len",False)(VFFSL(SL,"params",True)) == 1: # generated from line 3, col 1
            _v = VFFSL(SL,"module_name",True) # u'$module_name' on line 4, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$module_name')) # from line 4, col 1.
            write(u''' #(''')
            _v = VFN(VFFSL(SL,"params",True)[0],"value",True) # u'${params[0].value}' on line 4, col 16
            if _v is not None: write(_filter(_v, rawExpr=u'${params[0].value}')) # from line 4, col 16.
            write(u''') ''')
            _v = VFFSL(SL,"instance_name",True) # u'${instance_name}' on line 4, col 36
            if _v is not None: write(_filter(_v, rawExpr=u'${instance_name}')) # from line 4, col 36.
            write(u'''(
''')
        else: # generated from line 5, col 1
            _v = VFFSL(SL,"module_name",True) # u'$module_name' on line 6, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$module_name')) # from line 6, col 1.
            write(u''' #(
''')
            i = 1
            for param in VFFSL(SL,"params",True): # generated from line 8, col 5
                if VFFSL(SL,"i",True) != VFFSL(SL,"len",False)(VFFSL(SL,"params",True)): # generated from line 9, col 5
                    write(u'''    .''')
                    _v = VFFSL(SL,"param.name",True) # u'${param.name}' on line 10, col 6
                    if _v is not None: write(_filter(_v, rawExpr=u'${param.name}')) # from line 10, col 6.
                    write(u'''(''')
                    _v = VFFSL(SL,"param.value",True) # u'${param.value}' on line 10, col 20
                    if _v is not None: write(_filter(_v, rawExpr=u'${param.value}')) # from line 10, col 20.
                    write(u'''),
''')
                else: # generated from line 11, col 5
                    write(u'''    .''')
                    _v = VFFSL(SL,"param.name",True) # u'${param.name}' on line 12, col 6
                    if _v is not None: write(_filter(_v, rawExpr=u'${param.name}')) # from line 12, col 6.
                    write(u'''(''')
                    _v = VFFSL(SL,"param.value",True) # u'${param.value}' on line 12, col 20
                    if _v is not None: write(_filter(_v, rawExpr=u'${param.value}')) # from line 12, col 20.
                    write(u''')
''')
                i = VFFSL(SL,"i",True) + 1
            write(u''') ''')
            _v = VFFSL(SL,"instance_name",True) # u'${instance_name}' on line 16, col 3
            if _v is not None: write(_filter(_v, rawExpr=u'${instance_name}')) # from line 16, col 3.
            write(u'''(
''')
        i = 1
        for port in VFFSL(SL,"ports",True): # generated from line 19, col 1
            if VFFSL(SL,"i",True) != VFFSL(SL,"len",False)(VFFSL(SL,"ports",True)): # generated from line 20, col 5
                write(u'''    .''')
                _v = VFFSL(SL,"port.name",True) # u'${port.name}' on line 21, col 6
                if _v is not None: write(_filter(_v, rawExpr=u'${port.name}')) # from line 21, col 6.
                write(u'''(''')
                _v = VFFSL(SL,"port.value",True) # u'${port.value}' on line 21, col 19
                if _v is not None: write(_filter(_v, rawExpr=u'${port.value}')) # from line 21, col 19.
                write(u'''),
''')
            else: # generated from line 22, col 5
                write(u'''    .''')
                _v = VFFSL(SL,"port.name",True) # u'${port.name}' on line 23, col 6
                if _v is not None: write(_filter(_v, rawExpr=u'${port.name}')) # from line 23, col 6.
                write(u'''(''')
                _v = VFFSL(SL,"port.value",True) # u'${port.value}' on line 23, col 19
                if _v is not None: write(_filter(_v, rawExpr=u'${port.value}')) # from line 23, col 19.
                write(u''')
''')
            i = VFFSL(SL,"i",True) + 1
        write(u''');
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_module_instantiation= 'respond'

## END CLASS DEFINITION

if not hasattr(module_instantiation, '_initCheetahAttributes'):
    templateAPIClass = getattr(module_instantiation, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(module_instantiation)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=module_instantiation()).run()


