#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1407099852.304157
__CHEETAH_genTimestamp__ = 'Sun Aug  3 14:04:12 2014'
__CHEETAH_src__ = '../templates/rom.tmpl'
__CHEETAH_srcLastModified__ = 'Sun Aug  3 14:03:29 2014'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class rom(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(rom, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''module ''')
        _v = VFFSL(SL,"name",True) # u'${name}' on line 1, col 8
        if _v is not None: write(_filter(_v, rawExpr=u'${name}')) # from line 1, col 8.
        write(u'''(
    input clk,
    input [''')
        _v = VFFSL(SL,"addr_width",True) # u'$addr_width' on line 3, col 12
        if _v is not None: write(_filter(_v, rawExpr=u'$addr_width')) # from line 3, col 12.
        write(u''' - 1: 0] addr,
    output [''')
        _v = VFFSL(SL,"dout_width",True) # u'$dout_width' on line 4, col 13
        if _v is not None: write(_filter(_v, rawExpr=u'$dout_width')) # from line 4, col 13.
        write(u''' - 1: 0] dout,
);

always @(posedge clk) begin
    case (addr)
''')
        addr = 1
        for value in VFFSL(SL,"dout_vals",True): # generated from line 10, col 9
            write(u'''        ''')
            _v = VFFSL(SL,"addr_width",True) # u'${addr_width}' on line 11, col 9
            if _v is not None: write(_filter(_v, rawExpr=u'${addr_width}')) # from line 11, col 9.
            write(u"""'d""")
            _v = VFFSL(SL,"addr",True) # u'${addr}' on line 11, col 24
            if _v is not None: write(_filter(_v, rawExpr=u'${addr}')) # from line 11, col 24.
            write(u''': dout <= ''')
            _v = VFFSL(SL,"value",True) # u'${value}' on line 11, col 41
            if _v is not None: write(_filter(_v, rawExpr=u'${value}')) # from line 11, col 41.
            write(u''';
''')
            addr = VFFSL(SL,"addr",True) + 1
        write(u'''        default: dout <= ''')
        _v = VFFSL(SL,"addr_width",True) # u'${addr_width}' on line 14, col 26
        if _v is not None: write(_filter(_v, rawExpr=u'${addr_width}')) # from line 14, col 26.
        write(u"""'d0;
    endcase 
end 

endmodule
""")
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_rom= 'respond'

## END CLASS DEFINITION

if not hasattr(rom, '_initCheetahAttributes'):
    templateAPIClass = getattr(rom, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(rom)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=rom()).run()


