#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1407134300.842997
__CHEETAH_genTimestamp__ = 'Sun Aug  3 23:38:20 2014'
__CHEETAH_src__ = 'templates/wire.tmpl'
__CHEETAH_srcLastModified__ = 'Sun Aug  3 23:27:29 2014'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class wire(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(wire, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        for wire in VFFSL(SL,"wires",True): # generated from line 1, col 1
            if VFFSL(SL,"wire.width",True) > 1: # generated from line 2, col 1
                w = VFFSL(SL,"wire.width",True) - 1
                write(u'''wire [''')
                _v = VFFSL(SL,"w",True) # u'$w' on line 4, col 7
                if _v is not None: write(_filter(_v, rawExpr=u'$w')) # from line 4, col 7.
                write(u''': 0] ''')
                _v = VFFSL(SL,"wire.name",True) # u'$wire.name' on line 4, col 14
                if _v is not None: write(_filter(_v, rawExpr=u'$wire.name')) # from line 4, col 14.
                write(u''';
''')
            else: # generated from line 5, col 1
                write(u'''wire ''')
                _v = VFFSL(SL,"wire.name",True) # u'$wire.name' on line 6, col 6
                if _v is not None: write(_filter(_v, rawExpr=u'$wire.name')) # from line 6, col 6.
                write(u''';
''')
        for reg in VFFSL(SL,"regs",True): # generated from line 9, col 1
            if VFFSL(SL,"reg.width",True) > 1: # generated from line 10, col 1
                w = VFFSL(SL,"reg.width",True) - 1
                write(u'''reg [''')
                _v = VFFSL(SL,"w",True) # u'$w' on line 12, col 6
                if _v is not None: write(_filter(_v, rawExpr=u'$w')) # from line 12, col 6.
                write(u''': 0] ''')
                _v = VFFSL(SL,"reg.name",True) # u'$reg.name' on line 12, col 13
                if _v is not None: write(_filter(_v, rawExpr=u'$reg.name')) # from line 12, col 13.
                write(u''';
''')
            else: # generated from line 13, col 1
                write(u'''reg ''')
                _v = VFFSL(SL,"reg.name",True) # u'$reg.name' on line 14, col 5
                if _v is not None: write(_filter(_v, rawExpr=u'$reg.name')) # from line 14, col 5.
                write(u''';
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_wire= 'respond'

## END CLASS DEFINITION

if not hasattr(wire, '_initCheetahAttributes'):
    templateAPIClass = getattr(wire, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(wire)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=wire()).run()


